#!/bin/sh
set -e

if [ "$1" = "purge" ]; then
  rm -f /etc/nginx/sites-available/iosm.conf
  rm -f /etc/nginx/sites-enabled/iosm.conf
  rm -rf /etc/iosm
fi

if [ -d /run/systemd/system ]; then
  systemctl daemon-reload || true
  systemctl reload nginx || true
fi

exit 0
